version: '3'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80" 
    networks:
      - app-network


networks:
  app-network:
    driver: bridge