services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80" 
    networks:
      - app-network

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile 
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production 
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mydatabase
    networks:
      - app-network
    depends_on:
      - db  

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
